version: '3'

services:
  rails:
    build:
      context: .
      dockerfile: ./.docker/rails/Dockerfile
    command: rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql

volumes:
  db_data: